version: "3"
services:
  likes:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - app-network
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pra123156
      - POSTGRES_DB=likes
    volumes:
      - db-data:/var/lib/postgresql@15.3/data
    networks:
      - app-network
networks:
  app-network:
volumes:
  db-data:
